In [1]:
import numpy as np
import scipy

from IPython.display import display, Latex

In [2]:
# linear map R^3 to R^5
X = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,11],
    [-1,1,1],
    [13,17,25]
])

y = np.array([7, 13, 21, 23, 91]) # example point in simplex (R^5)

In [3]:
np.linalg.matrix_rank(X)

np.int64(3)

In [4]:
_, _, pivot = scipy.linalg.qr(X.T, pivoting=True)
basis_rows = pivot[:3]
dependent_rows = pivot[3:]
print(f"rows {dependent_rows} are lin. comb. of rows {basis_rows}")

rows [2 0] are lin. comb. of rows [4 3 1]


In [5]:
A = X[basis_rows].T
b = X[dependent_rows].T
print(f"{A}\n\n{b}")

[[13 -1  4]
 [17  1  5]
 [25  1  6]]

[[ 7  1]
 [ 8  2]
 [11  3]]


In [6]:
c = np.linalg.solve(A, b)
c

array([[ 0.28571429,  0.14285714],
       [-0.42857143,  0.28571429],
       [ 0.71428571, -0.14285714]])

In [7]:
X[basis_rows].T @ c[:,0]

array([ 7.,  8., 11.])

In [8]:
X[basis_rows].T @ c[:,1]

array([1., 2., 3.])

In [9]:
display(Latex(rf"For $\mathbf{{y}}\in\mathbb{{R}}^5$ to be a feasible point in the simplex we must have that elements {dependent_rows} of $\mathbf{{y}}$ are **the same** lin. comb. of elements {basis_rows} of $\mathbf{{y}}$"))

<IPython.core.display.Latex object>

In [10]:
(y[basis_rows].T @ c[:,0] == y[2]) and (y[basis_rows].T @ c[:,1] == y[0])

np.False_

In [11]:
coeffs, residuals, rank, sv = np.linalg.lstsq(X, y, rcond=None)

In [12]:
X @ coeffs

array([17.125     , 11.91666667, 24.54166667, 21.625     , 88.54166667])

In [13]:
residuals

array([124.16666667])

In [14]:
sv

array([37.50507992,  1.9251034 ,  0.81422177])